### ISSUE TITLE
Login Allow Custom Headers

### ISSUE THREAD

**Issue by ryanramage** [UsabilityDynamics/node-rets-client#12]
As related to #10 , I have RETS providers that need a specific User-Agent header value. I am going to patch the login methods to take an optional config object. You will be able to add headers to that config object.

**Comment by dermidgen** [comment]
@ryanramage please refer to https://github.com/dermidgen/node-rets-client/tree/develop

This effort is being moved to https://github.com/retsr/rets.js as the @UsabilityDynamics folks have been unresponsive for more than a year.

My #develop branch offers the features you need. In the coming weeks rets.js will more cleanly offer these features and more.

**Comment by ryanramage** [comment]
@dermidgen thanks for pointing this forks out to me. I will move to trying out/contributing to both where I can.

**Comment by ryanramage** [comment]
@dermidgen  Darn, node-curl does not like iojs (seems https://github.com/jiangmiao/node-curl/issues/38) relevant.

I guess I could take a crack at the query in the rets.js to finish the functionality I would need...

**Comment by dermidgen** [comment]
Yeah another reason for the rets.js effort. It's very early stage but hopefully by today I will have search and metadata calls in there - as well as completed user agent auth. Basically, we are porting the work from my branch here and going as native as possible (so io.js should be cool - no more libcurl and hopefully no more expat).
